### ISSUE TITLE
.NET Core

### ISSUE THREAD

**Issue by HamedFathi** [npodbielski/Delegates#1]
Hi
Thank you so much for your codes !
Can you support .NET Core too ?

I tried to convert your project to .NET Core but I had some problems with GetMethod() and GetConstructor(),
so Can you release .NET Core version ?

**Comment by npodbielski** [comment]
Did you created Core version fork I could look at?

**Comment by HamedFathi** [comment]
@npodbielski 

sure, I wanted to pull a request for .NET Core version but because of two errors that comes from two overloads 

1. GetMethod(name, BindingFlags.Instance | BindingFlags.Public, null, parametersTypes, null)
2. GetConstructor(BindingFlags.Public, null, types, null)

in .NET Core, I share zip file here.
If you have time please check this.

[Delegates.zip](https://github.com/npodbielski/Delegates/files/669080/Delegates.zip)

**Comment by npodbielski** [comment]
Check new version. I updated quite a lot.

**Comment by HamedFathi** [comment]
Thank you so much
