### ISSUE TITLE
Spelling: constructors are called contructors in your DelegateFactory class

### ISSUE THREAD

**Issue by mawibo** [npodbielski/Delegates#3]
Hi,

Title says it all.

Maarten

**Comment by npodbielski** [comment]
Funny. I obviously made a mistake and then copy and copy it all over library :)

**Comment by mawibo** [comment]
I installed version 1.1.0 via NuGet, but the typo is still present.
Maarten

**Comment by npodbielski** [comment]
I had a bug in my publishing script. Fixed now. Checkout new version. I added new features.

**Comment by mawibo** [comment]
Hi,
Typo is indeed fixed now. What are the new features?
Maarten
P.S.: thanks for your excellent work!

**Comment by npodbielski** [comment]
I added EventIvoke, which creates delegates for invoking an events.
Standard implementation:
`Event?.Invoke(sender, args);`
